version: 0.2

env:
  variables:
    ELASTICSEARCH_NODES: ""
    TENANT_CLAIM: "custom:tenant"
    SLS_DEBUG: "*"
    SERVERLESS_DEPLOYMENT_STAGE: "int"
    SERVERLESS_DEPLOYMENT_REGION: "eu-west-1"

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - node_modules/serverless/bin/serverless deploy --stage $SERVERLESS_DEPLOYMENT_STAGE --region $SERVERLESS_DEPLOYMENT_REGION --verbose

#artifacts:
  #files:
    #- serverless.yml
    #- ./.serverless/*
    #- cloudformation-template-create-stack.json
    #- ./.serverless/insight-data-api.zip
    #- deploy.out
  #discard-paths: yes
  