version: 0.2

env:
  variables:
    ELASTICSEARCH_NODES: ""
    TENANT_CLAIM: "custom:tenant"
    SLS_DEBUG: "*"    
    DEPLOYMENT_STAGE: "dev"
    DEPLOYMENT_REGION: "eu-west-1"

phases:
  install:
    commands:      
      - npm install -g serverless
      - npm install serverless-plugin-webpack --save-dev
      #- npm install serverless-plugin-git-variables --save-dev
      - npm install serverless-plugin-tracing --save-dev
      - npm install
  build:
    commands:
      - serverless deploy --stage $DEPLOYMENT_STAGE --region $DEPLOYMENT_REGION --verbose
      #- serverless package
      #- serverless deploy --stage dev --verbose
  #post_build:
    #commands:
      #- mv ./deploymentspec.yml ./.serverless/buildspec.yml

artifacts:
  files:
    - serverless.yml
    - buildspec*.yml
    - ./.serverless/*
    #- cloudformation-template-create-stack.json
    #- ./.serverless/insight-data-api.zip
    #- deploy.out
  discard-paths: yes
  