version: 0.2

env:
  variables:
    ELASTICSEARCH_NODES: ""
    TENANT_CLAIM: "custom:tenant"
    SLS_DEBUG: "*"    
    SERVERLESS_DEPLOYMENT_STAGE: "dev"
    SERVERLESS_DEPLOYMENT_REGION: "eu-west-1"
  #parameter-store:
    #var_name: param_store_var_name

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run test
      - node_modules/serverless/bin/serverless deploy --stage $SERVERLESS_DEPLOYMENT_STAGE --region $SERVERLESS_DEPLOYMENT_REGION --verbose
      #- serverless package
  #post_build:
    #commands:
      #- mv ./deploymentspec.yml ./.serverless/buildspec.yml

artifacts:
  files:
    - ./test-coverage/**/*
    #- serverless.yml
    #- buildspec*.yml
    #- ./.serverless/*
    ##- cloudformation-template-create-stack.json
    ##- ./.serverless/insight-data-api.zip
    ##- deploy.out
  #discard-paths: yes
  