version: 0.2

env:
  variables:
    ELASTICSEARCH_NODES: ""
    TENANT_CLAIM: "custom:tenant"

phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - serverless package

artifacts:
  files:
    - serverless.yml
    - ./.serverless/cloudformation-template-create-stack.json
    - ./.serverless/insight-data-api.zip
  discard-paths: yes
  