version: 0.2

env:
  variables:
    ELASTICSEARCH_NODES: ""
    TENANT_CLAIM: "custom:tenant"
    SLS_DEBUG: "*"

phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
      - npm install serverless-plugin-webpack --save-dev
      - npm install serverless-plugin-git-variables --save-dev
      - npm install serverless-plugin-tracing
  build:
    commands:
      - serverless package
      #- serverless deploy --stage dev --verbose

artifacts:
  files:
    - serverless.yml
    - ./.serverless/cloudformation-template-create-stack.json
    - ./.serverless/insight-data-api.zip
    #- deploy.out
  discard-paths: yes
  