service:
  name: ${file(package.json):name}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-git-variables
  # Note that this plugin is a stop-gap measure until official xray support is added to Serverless. 
  # This work is being tracked here: https://github.com/serverless/serverless/issues/3495
  - serverless-plugin-tracing

package:
  individually: false

provider:
  name: aws
  region: eu-west-1
  memorySize: 128
  stage: dev
  runtime: nodejs6.10
  environment:
    ELASTICSEARCH_NODES: ${env:ELASTICSEARCH_NODES}
    TENANT_CLAIM: ${env:TENANT_CLAIM}
  tracing: true
  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

functions:
  get:
    handler: src/data/get.get
    description: Built from ${git:sha1} on branch ${git:branch}
    events:
      - http:
          path: data/{type}/{id}
          method: get
          #authorizer:
            #arn: ${env:COGNITO_AUTHORIZER_ARN}
  create:
    handler: src/data/create.create
    description: Built from ${git:sha1} on branch ${git:branch}
    events:
      - http:
          path: data/{type}
          method: post
          #authorizer:
            #arn: ${env:COGNITO_AUTHORIZER_ARN}
  update:
    handler: src/data/update.update
    description: Built from ${git:sha1} on branch ${git:branch}
    events:
      - http:
          path: data/{type}/{id}
          method: put
          #authorizer:
            #arn: ${env:COGNITO_AUTHORIZER_ARN}
  delete:
    handler: src/data/delete.delete
    description: Built from ${git:sha1} on branch ${git:branch}
    events:
      - http:
          path: data/{type}/{id}
          method: delete
          #authorizer:
            #arn: ${env:COGNITO_AUTHORIZER_ARN}
  debug:
    handler: src/debug/info.info
    description: Built from ${git:sha1} on branch ${git:branch}
    events:
      - http:
          path: debug
          method: get
          #authorizer:
            #arn: ${env:COGNITO_AUTHORIZER_ARN}